// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8FG-3If0GXwcBe6eIGGLqhM4QEBU50Ng',
    appId: '1:1088416908944:web:5684cc3d74c6f3a427fa15',
    messagingSenderId: '1088416908944',
    projectId: 'studentapp-lux',
    authDomain: 'studentapp-lux.firebaseapp.com',
    storageBucket: 'studentapp-lux.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZXQJMmPdNWHKIqCF4dukJCmKj3cDsNmY',
    appId: '1:1088416908944:android:66046ecf864a8a1927fa15',
    messagingSenderId: '1088416908944',
    projectId: 'studentapp-lux',
    storageBucket: 'studentapp-lux.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJoyw32XtbnNErQ41kOsxQjphtMMg9Psw',
    appId: '1:1088416908944:ios:d0b4872b2feb28ad27fa15',
    messagingSenderId: '1088416908944',
    projectId: 'studentapp-lux',
    storageBucket: 'studentapp-lux.firebasestorage.app',
    iosBundleId: 'com.example.lux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJoyw32XtbnNErQ41kOsxQjphtMMg9Psw',
    appId: '1:1088416908944:ios:d0b4872b2feb28ad27fa15',
    messagingSenderId: '1088416908944',
    projectId: 'studentapp-lux',
    storageBucket: 'studentapp-lux.firebasestorage.app',
    iosBundleId: 'com.example.lux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8FG-3If0GXwcBe6eIGGLqhM4QEBU50Ng',
    appId: '1:1088416908944:web:f007e2f904a73caf27fa15',
    messagingSenderId: '1088416908944',
    projectId: 'studentapp-lux',
    authDomain: 'studentapp-lux.firebaseapp.com',
    storageBucket: 'studentapp-lux.firebasestorage.app',
  );
}
